name: 'Python SDK Test Steps'
description: 'Runs tests for the Python SDK'

runs:
  using: "composite"
  steps:

    # =================================================
    # Setup
    # =================================================

    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install UV
      shell: bash
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      shell: bash
      run: |
        cd client_sdks/python
        uv sync --dev

    # =================================================
    # Tests
    # We run all tests except benchmarks
    # =================================================

    - name: Run tests
      shell: bash
      env:
        MANAGER_TEST_URL: http://localhost:3000
        BROKER_TEST_URL: amqp://user:password@localhost:5672
      run: |
        cd client_sdks/python
        uv run pytest -m "not bench"

    # =================================================
    # Benchmarks
    # =================================================

    - name: Create benchmark output file
      shell: bash
      run: |
        cd client_sdks/python
        touch output.json

    - name: Run benchmarks
      shell: bash
      run: |
        cd client_sdks/python
        uv run pytest -m "bench" --benchmark-json output.json

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'pytest'
        output-file-path: output.json
