name: Rust CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: Run sqlx prepare
        run: cargo sqlx prepare --workspace
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Commit changes if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add .
            CHANGES=""
            git diff --cached --name-only | while read -r file; do
              if [[ $file == .sqlx/* ]]; then
                CHANGES="sqlx-data"
              elif [[ $file == *.rs ]]; then
                if grep -q "^[+-]" <(git diff --cached -U0 "$file") ; then
                  if [[ -z $CHANGES ]]; then
                    CHANGES="formatting"
                  else
                    CHANGES="$CHANGES and formatting"
                  fi
                fi
              fi
            done
            
            git commit -m "chore: automatic ${CHANGES} update"
            git push
          fi

  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    needs: prepare
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --target builder -t app-builder -f server/services/galactus/Dockerfile
      - name: Create test database and run migrations
        run: |
          docker run --network host \
            -e DATABASE_URL=${DATABASE_URL} \
            app-builder sqlx database create
          docker run --network host \
            -e DATABASE_URL=${DATABASE_URL} \
            app-builder sqlx migrate run --source ./server/libs/db-common/migrations
      - name: Run tests in container
        run: |
          docker run --network host \
            -e DATABASE_URL=${DATABASE_URL} \
            app-builder cargo test --all-features
