name: Publish Python SDK

on:
  push:
    tags:
      - 'general@*' # General Lockstep Release. Releases a new version of everything.
      - 'python@*' # Python Release. Only releases a new version of the Python SDK.

jobs:

  publish_python_sdk:
    name: Publish Python SDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag version
        uses: ./.github/actions/extract_version
        id: version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build package
        run: |
          cd client_sdks/python
          uv build

      - name: Verify versions match
        run: |
          cd client_sdks/python
          uv venv
          uv sync
          PACKAGE_VERSION=$(uv pip show tacoq | grep Version | cut -d' ' -f2)
          if [ "$PACKAGE_VERSION" != "${{ steps.version.outputs.version }}" ]; then
            echo "Version mismatch! Tag version: ${{ steps.version.outputs.version }}, Package version: $PACKAGE_VERSION"
            echo "Please update the version in the release tag and pyproject.toml so that they are compatible and try again."
            exit 1
          fi

      - name: Publish package to PyPI
        run: |
          cd client_sdks/python
          uv publish
