name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/services/manager/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/manager:latest
            ghcr.io/${{ github.repository }}/manager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
