name: Code Quality - Python

on:
  pull_request:
    branches:
      - main
    paths:
      - 'client_sdks/python/**'
      - '.github/**'

permissions:
  contents: read

jobs:
  python-quality:
    name: Ruff Linting & Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Check formatting & linting
        run: |
          cd client_sdks/python
          uv tool run ruff format --check .
          uv tool run ruff check .
