name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rust checks
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy --all-features --tests -- -D warnings

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Run sqlx prepare
        run: cargo sqlx prepare --workspace --check
        env:
          SQLX_OFFLINE: true

      # Python checks
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Check Python formatting
        run: |
          cd client_sdks/python
          uv tool run ruff format --check .

      - name: Run Python linter
        run: |
          cd client_sdks/python
          uv tool run ruff check .
