name: Relay Code Quality

on:
  pull_request:
    branches:
      - main
    paths:
      - 'relay/**'
      - '.github/**'

permissions:
  contents: read

jobs:

  rust-fmt:
    name: Cargo Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check code formatting
        run: cargo fmt --all -- --check

  rust-clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Check clippy
        run: cargo clippy --all-features --tests -- -D warnings

  rust-sqlx:
    name: SQLx Schema Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: Run sqlx prepare
        run: cargo sqlx prepare --workspace --check
        env:
          SQLX_OFFLINE: true